# Generated by Django 5.2.15 on 2026-06-10 13:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('churches', '0001_initial'),
        ('fundraising', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Incoming (Donation)'), ('out', 'Outgoing (Disbursement/Payout)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('reference', models.CharField(db_index=True, help_text='Internal reference we sent (e.g. CAMP-uuid or DISB-xxx)', max_length=120)),
                ('provider', models.CharField(default='keshopay', max_length=30)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('raw_request', models.JSONField(blank=True, default=dict)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('webhook_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='churches.church')),
                ('related_disbursement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='fundraising.disbursement')),
                ('related_donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='fundraising.donation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['church', 'status'], name='payments_pa_church__dae95e_idx'), models.Index(fields=['provider_reference'], name='payments_pa_provide_ddbf17_idx')],
            },
        ),
    ]
