# Generated by Django 5.2.15 on 2026-06-10 19:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='current_fund_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='church',
            name='member_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='church',
            name='plan',
            field=models.CharField(choices=[('Starter', 'Starter'), ('Growth', 'Growth'), ('Enterprise', 'Enterprise')], default='Starter', max_length=20),
        ),
        migrations.AddField(
            model_name='church',
            name='wellness_avg',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='pastor',
            name='assessment_due',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pastor',
            name='counselor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['counselor', 'cfs_counselor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pastors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pastor',
            name='counselor_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='pastor',
            name='status',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Stable', 'Stable'), ('Monitor', 'Monitor'), ('At Risk', 'At Risk')], default='Stable', max_length=20),
        ),
        migrations.AddField(
            model_name='pastor',
            name='wellness_score',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='pastor',
            name='years_of_service',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ChurchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Conference', 'Conference'), ('Webinar', 'Webinar'), ('Retreat', 'Retreat'), ('Workshop', 'Workshop'), ('Service', 'Service'), ('Other', 'Other')], default='Other', max_length=30)),
                ('format', models.CharField(choices=[('In-person', 'In-person'), ('Online', 'Online'), ('Hybrid', 'Hybrid')], default='In-person', max_length=20)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('registered', models.PositiveIntegerField(default=0)),
                ('fee', models.CharField(default='Free', max_length=50)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Almost Full', 'Almost Full'), ('Planning', 'Planning'), ('Closed', 'Closed'), ('Recurring', 'Recurring')], default='Open', max_length=20)),
                ('is_cfs_event', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='churches.church')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cfs', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=150)),
                ('type', models.CharField(choices=[('Article', 'Article'), ('Video', 'Video'), ('Audio', 'Audio'), ('Toolkit', 'Toolkit')], default='Article', max_length=20)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('audience', models.CharField(blank=True, max_length=50)),
                ('views', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=20)),
                ('date', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='churches.church')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('cell_group', models.CharField(blank=True, max_length=100)),
                ('ministry', models.CharField(blank=True, max_length=100)),
                ('attendance', models.CharField(default='Regular', max_length=50)),
                ('baptized', models.BooleanField(default=False)),
                ('status', models.CharField(default='Active', max_length=30)),
                ('joined', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='churches.church')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('assignee_name', models.CharField(blank=True, max_length=150)),
                ('due_date', models.CharField(blank=True, max_length=50)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='Pending', max_length=20)),
                ('done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='churches.church')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WellnessAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField(auto_now_add=True)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('overall_score', models.PositiveIntegerField(default=50)),
                ('dimension_scores', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pastor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='churches.pastor')),
            ],
            options={
                'ordering': ['-assessment_date'],
            },
        ),
    ]
