# Generated by Django 5.2.15 on 2026-06-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('cfs_superadmin', 'CFS Super Admin'), ('cfs_admin', 'CFS Super Admin'), ('cfs_staff', 'CFS Staff'), ('church_admin', 'Church Admin'), ('finance_officer', 'Finance Officer'), ('pastor', 'Pastor'), ('ministry_leader', 'Ministry Leader'), ('counselor', 'Counselor'), ('church_member', 'Church Member'), ('donor', 'Donor / Partner')], default='church_member', max_length=30),
        ),
    ]
