# Generated by Django 5.2.15 on 2026-06-10 13:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('churches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. "Pastor James Sabbatical Fund"', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='churches.church')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('pastor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='churches.pastor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purpose', models.TextField(help_text="e.g. 'The Sabbath Week retreat for Pastor James at Lake Naivasha'")),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], db_index=True, default='requested', max_length=20)),
                ('payout_phone', models.CharField(help_text='M-Pesa number that will receive the funds', max_length=20)),
                ('payout_reference', models.CharField(blank=True, help_text='KeshoPay or manual payout ref', max_length=100)),
                ('proof_notes', models.TextField(blank=True, help_text='Description of what the funds were used for + any reference numbers')),
                ('proof_file', models.FileField(blank=True, help_text='Optional receipt, invoice, booking confirmation etc. Stored on server MEDIA_ROOT', null=True, upload_to='disbursement_proofs/')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_disbursements', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to='fundraising.campaign')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='churches.church')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_disbursements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_phone', models.CharField(db_index=True, max_length=20)),
                ('donor_name', models.CharField(blank=True, max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('next_due_date', models.DateField(blank=True, help_text='When to expect next contribution', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='fundraising.campaign')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='churches.church')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_phone', models.CharField(db_index=True, max_length=20)),
                ('donor_name', models.CharField(blank=True, max_length=150)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Successful'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('kesho_reference', models.CharField(blank=True, db_index=True, help_text='Our reference sent to KeshoPay', max_length=100)),
                ('provider_transaction_id', models.CharField(blank=True, db_index=True, help_text='KeshoPay transactionId', max_length=100)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='fundraising.campaign')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='churches.church')),
                ('pledge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='fundraising.pledge')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['church', 'status'], name='fundraising_church__fbf4ef_idx'), models.Index(fields=['campaign', 'status'], name='fundraising_campaig_d3a335_idx')],
            },
        ),
    ]
