# Generated by Django 5.2.15 on 2026-06-10 19:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('churches', '0002_church_current_fund_balance_church_member_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselingCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Regular', max_length=30)),
                ('status', models.CharField(choices=[('Unassigned', 'Unassigned'), ('Active', 'Active'), ('On Hold', 'On Hold'), ('Closed', 'Closed')], default='Unassigned', max_length=20)),
                ('priority', models.CharField(choices=[('high', 'high'), ('medium', 'medium'), ('normal', 'normal')], default='normal', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counseling_cases', to='churches.church')),
                ('pastor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counseling_cases', to='churches.pastor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CounselingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=50)),
                ('time', models.CharField(blank=True, max_length=30)),
                ('type', models.CharField(default='Regular', max_length=30)),
                ('format', models.CharField(default='Video Call', max_length=30)),
                ('status', models.CharField(choices=[('Unassigned', 'Unassigned'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Scheduled', max_length=20)),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='counseling.counselingcase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('speciality', models.CharField(blank=True, max_length=150)),
                ('available', models.BooleanField(default=True)),
                ('sessions_total', models.PositiveIntegerField(default=0)),
                ('active_cases', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counselor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='counselingcase',
            name='counselor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='counseling.counselor'),
        ),
    ]
